language: php
sudo: false
env:
  matrix:
  - JQUERY=1
  - JQUERY=2
  - JQUERY=3
  - DOCUMENTATION=1
  global:
    GIT_NAME: "'Couscous auto deploy'"
    GIT_EMAIL: couscous@couscous.io
    GH_REF: github.com/swisnl/jQuery-contextMenu
    secure: XaE2bPODLwmzaNAKv9pA8mMiXJc8OrpyrO5tIGuOCwfQ+q7hx6Xa/tTcyn5+H2g+xYyJ0Qqv5+SDkDxbbgaVJLR1VEW15KEcZbD/3speqkg+yIC/oFxgbf1Ib01f0FowR2cw4/5Y2XzCM8CU7UxOLFGBDDCvM39Ab3UUl4uB/8g=
install:
- if [ "$JQUERY" ] ; then nvm install stable && npm install && npm install jquery@$JQUERY && npm test ; fi
- if [ "$DOCUMENTATION" ] ; then cd documentation && composer require couscous/couscous && vendor/bin/couscous generate ; fi
script: echo "No PHP tests"
